=== Description de la proposition
*_Note: 2 page max._*

_Décrire de façon détaillée votre projet : motivations de base/problèmes
constatés avant élaboration du projet, comment votre projet répond à ces
besoins. Ajouter une image ou une figure pour montrer à quoi cela
ressemble si besoin._

Le projet consiste en la conception d’un objet portable, discret, potentiellement sous la forme d’un bipeur, qui permettrait d’alerter les membres du pôle REC (pôle de prévention contre les violences sexistes et sexuelles) en cas de VSS (violences sexistes et sexuelles), ou de tout autre problème lors des soirées télécomiennes ou avec d’autres écoles. La victime serait alors géolocalisée dans la soirée, ce qui aiderait à l’intervention rapide des membres du pôle REC grâce à l’alerte reçue. Le dispositif, pensé pour être utilisé à Télécom, pourrait ensuite être étendu à d’autres écoles. L’ensemble du projet regroupait au premier abord différents enjeux à traiter.

Nous devrions créer une application (interface entre l’utilisateur et l’objet), qui permettra aux utilisateurs de communiquer leur données (photos, nom, prénom…). Pour le pôle REC, cette application permettrait en particulier d’informer ses membres lors d’une agression. Différentes questions se posent : Quelles seront les données à transmettre ? Par quelle plateforme (application, site web...) se fait la première connexion ? Le projet nécessite aussi la gestion d’un réseau. Les bipeurs doivent transmettre un signal reçu par les téléphones du pole REC (a priori par l’intermédiaire de balise et d’un serveur). Nous devons donc transmettre des informations par onde électromagnétiques. De plus, toute cette installation demande une bonne gestion de l’aspect « hardware » (électronique, balise, antenne...) du projet pour pouvoir envoyer et réceptionner un signal lorsqu’une victime appuie sur un bipeur. De même, la géolocalisation est un enjeux clé de la réussite du système. Une question fondamentale est celle de la technologie utilisée : Est-il possible de mettre en place un dispositif de géolocalisation, à l’extérieur ou à l’intérieur qui localiserait la victime avec assez de précision ? Quelle est cette précision nécessaire ? Une fois les difficultés techniques surmontées, une réflexion sur l’éthique de nos méthodes s’impose. Comment préserver l’anonymat des victimes ? Quelles données sont transmises et à qui ?

Nous avons finalement décidé de réaliser un bracelet contenant une puce électronique. En effet, c’est un des formats les plus pratiques pour les étudiants. Par une simple pression sur le bracelet, un signal est envoyé et peut être capté. En premier lieu, nous avons pensé à une communication directe entre le bracelet et l’application, qui serait capable de capter les signaux envoyés en permanence. Cependant, avec les remarques de certains experts, nous avons compris d’une part qu’il était interdit de réaliser un tel système chez Samsung par exemple et que d’autre part cela utilise énormément de batterie. Par conséquent, nous avons décidé d’utiliser des balises qui capteraient les signaux du bracelet et pourraient envoyer des informations sur la position du bracelet à notre base de données. Ainsi, cette dernière calcule la position exacte et une notification est envoyée via l’application sur le téléphone des membres du pôle REC avec la localisation de la personne agressée. Les Rasperry Pi utilisées pour coder nos balises nous permettent donc de faire le lien entre le bracelet et la base de données. De cette manière, les utilisateurs auraient probablement besoin de se connecter qu’une seule fois sur l’application pour rentrer leurs informations personnelles (photo, école…) s’ils le souhaitent et l’application ne serait utilisée que par les membres du pôle REC le reste du temps. Notre bracelet répondrait donc à  3 critères : efficacité, facilité d’utilisation, esthétisme.


Au regard de la proportion d’étudiantes présentes à Telecom Paris (22%), à Centrale-Supélec (17%), à Polytechnique (18%), l’ambiance dans ces écoles d’ingénieur a tendance à être très masculine. Nous nous sommes donc plus particulièrement penchés sur les agressions dont les victimes seraient des étudiantes mais ce projet concerne évidemment la protection contre les VSS et violences autres sur des personnes de tout genre.