=== Interface utilisateur graphique
////
Il peut y avoir une ou plusieurs interfaces utilisateur (UI en anglais),
ou interface graphique, ou interface homme machine (IHM) : une interface
sur ordinateur et/ou une interface sur mobile ou tablette (Android),
selon le nombre d’appareils en jeu.

En lien avec un diagramme de séquence, une description simple de chaque
écran/page est nécessaire. Il est recommandé de faire des dessins, même
dessins au crayon, photographiés ou scannés, car ce sont les meilleurs
supports de discussion : on appelle souvent ces dessins un
« storyboard ». Une description textuelle fait le lien entre tous les
éléments de l’IHM (ou des IHMs).
////

Description du storyboard 

Pour la première connexion (interface étudiant-application): 

L'utilisateur peut créer son compte et y rentrer ses informations personnelles s'il le souhaite. 
Il se connecte ensuite à son bracelet et peut lancer une alerte par un appui sur le bouton de son bracelet.

Pour la première connexion ainsi qu'une connexion quelconque (interface pôle REC-application):

Le pôle REC reçoit une notification d'alerte (seulement s'il y a eu pression sur le bouton) avec le nom, le prénom, l'école (si l'étudiant a partagé ses données personnelles) et la géolocalisation. 
Un membre du pôle REC peut donc agir, et l'étudiant peut annuler son alerte à tout moment sur l'application. 