=== Description des interfaces (PAN1 / PAN2)

Pour le PAN1, il faut identifier et décrire sommairement toutes les
interfaces entre modules.

Pour le PAN2, il faut une description complète des interfaces.

Il faut ici une description textuelle de chaque interface, c'est-à-dire chaque
échange entre deux blocs.blabla
Si c’est une interface entre deux blocs informatiques, c’est une interface
Java.
S’il y a des échanges de données complexes, il faut en décrire le format avec
précision.
Si c’est une interface entre deux blocs électroniques, c’est une description
des signaux électroniques ou protocoles utilisés.

==== Interface Application mobile / Serveur

Interface Java qui permet l'envoi/la réception de requête entre l'application mobile et le serveur.

==== Interface Base De Données / Serveur

Interface Java qui permet l'envoi/la réception de requête entre la BDD et le serveur.

==== Interface Bracelet / Balises (RaspBerry Pi)

Ondes (certainement un échange bluetooth) échangées entre le bracelet et les balises. 

==== Interface Bracelet / Application mobile

Échange bluetooth entre l'application et le bracelet.
