
=== Schéma d’architecture

image::SchémaArchitecturalFinal.pdf[]
////
Insérer ici un ou plusieurs schémas d’architecture du projet. Voir le
cours d’introduction au Génie Logiciel. N’hésitez pas à faire des
schémas hiérarchiques, c'est-à-dire avec un bloc d’un schéma général
raffiné dans un second schéma ; ou des schémas en plusieurs parties.

*Exemple utilisant http://www.graphviz.org/Documentation.php[graphviz]*
Voir la liste des outils supportés par http://asciidoctor.org/docs/asciidoctor-diagram/[asciidoctor-diagram].
**(Vous pouvez, bien sûr, utiliser votre outil de dessin préféré).**

[graphviz, arch-diag, svg]
....
digraph MonGraph {
    graph [rankdir = LR, splines=ortho];

    node[shape=record];
    BlocIn[label="La source", height=2];
    Hub[label="Le «dispatcheur»", height=4];

    BlocOut1[label="Première sortie", height=2];
    BlocOut2[label="Seconde  Sortie", height=2];

    BlocIn -> Hub [label="Image"];
    BlocIn -> Hub [label="Son"];
    BlocIn -> Hub [label="Émotion"];

    Hub -> BlocOut1 [label="Musique"];
    Hub -> BlocOut1 [label="Chant"];
    BlocOut1 -> Hub [label="commande"];


    Hub -> BlocOut2 [label="Image"];
    Hub -> BlocOut2 [label="commande"];
}
....
////

==== Description des blocs
////
Il faut ici une description textuelle de chaque bloc, sa fonction
détaillée. En général, un bloc correspond à un module, sauf exception.
Il peut être adapté de faire des blocs plus petits qu’un module.
////

Il est important ici de distinguer les bibliothèques identifiées et
disponibles de ce que vous allez produire (coder) vous-même. Vous ne
devez pas réinventer la roue, mais vous ne devez pas non plus avoir votre
projet tout fait en encapsulant un programme déjà existant.

===== Bracelet utilisateur

Le bracelet permet à une potentielle victime d'alerter le pôle REC en 
cas de problème, en appuyant sur un bouton contenue dans le bracelet.
Le système contenue dans le bracelet envoie des signaux Bluetooth aux balises
Raspberry Pi, qui permettront de géolocaliser grossièrement le bracelet de la victime.

===== Balises Raspberry Pi

Le rôle des balises est de recevoir les signaux provenant des bracelets. En fonction de l'intensité
du signal perçu, la balise envoie un signal au serveur.
Nous utiliserons dans le bracelet un émetteur bluetooth préexistant, dont nous essayerons de programmer l'émission de signal pour que cela corresponde à nos attentes. 

===== Serveur

Le serveur reçoit les signaux des différentes balises, et calcule alors la position du bracelet.
Le serveur s'occupe aussi de recevoir des requêtes de connexion/création de compte provenant des téléphones 
utilisateurs. Il peut alors communiquer avec la BDD pour mettre à jour les données utilisateurs. 
Le serveur sera créé grâce au module correspondant.

===== Base De Données

La base de données stocke les différentes données utilisateurs: noms, prénoms, photos. 
La base de données sera créée grâce au module correspondant.

===== Application

L'application a deux versions interfaces différentes: une pour les membres du pôle REC, une pour les 
utilisateurs. Elle sera codée en React Native grâce au module correspondant.
Du côté utilisateur, l'interface permet de se créer/connecter à un compte, d'entrer ses informations
(photo, informations complémentaires), et éventuellement d'annuler une alerte déclenchée par erreur.
Du côté REc, l'interface permet de répondre à une alerte, de visualiser la position de la victime dans 
zone couverte par la géolocalisation, ainsi que d'afficher la photo de la personne appelant de l'aide.
////
*Exemple utilisant http://blockdiag.com/en/actdiag/index.html[actdiag]*
**(Vous pouvez, bien sûr, utiliser votre outil de dessin préféré).**

[actdiag, diag_activite, svg]
....
actdiag {
  ecrire -> convertir -> afficher

  lane user {
     label = "User"
     ecrire [label = "Décire les matrices"];
     afficher  [label = "Afficher la courbe"];
  }
  lane converter {
     label = "Convertisseur"
     convertir [label = "Convertir\n en utilisant\n@@"];
  }
}
....

Voir la liste des outils supportés par http://asciidoctor.org/docs/asciidoctor-diagram/[asciidoctor-diagram].
////